on:
  push:
    branches: [repo]
  pull_request:
    branches: [main]
  workflow_dispatch:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - uses: andyholmes/flatter@main
      with:
        files: org.rvgl.rvmm.yml
        upload-bundles: true
        upload-pages-artifact: true

  deploy:
    needs: flatpak
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: ${{ github.ref == 'refs/heads/repo' }}
    steps:
    - name: GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
